eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: 'localhost'
    #status-page-url-path: '/department/getdepartments'
management:
  endpoints:
    web:
      exposure:
        include: '*'
